### ISSUE TITLE
It doesn't work in Firefox 90.0.2

### ISSUE THREAD

**Issue by Qwerty-Space** [werty1st/popup2tab#1]

**Comment by werty1st** [comment]
Firefox reports the new Window as type "normal" and not "popup" like it should and how chrome does. I don't know if its a bug. I tested version 91, 89, 88, 82 and 76 but all report window.type="normal".

I'm sure the Addon was working when i released it for Firefox but I can't find the version I tested it with.

Unfortunately I don't know how to work around this so I can only remove the Addon from the Firefox Store. 

Sorry.

**Comment by Qwerty-Space** [comment]
Okay, fair enough.  

I have found a workaround for my use case.  Go to `about:config` and search for `browser.link.open_newwindow.restriction`, change the value to `0`.
