### ISSUE TITLE
Add an addition destination: Side panel

### ISSUE THREAD

**Issue by jussi01** [werty1st/popup2tab#2]
Hi, I'd love to have exactly this extension, except that the popup opens in a side panel, instead of the new tab?
Documentation for the side panel is here: https://developer.chrome.com/docs/extensions/reference/sidePanel/

I've been trying to get my own head around doing it and offering a patch, however unfortunately I haven't got it working. 

Let me know if there is motivation on your side - I'd appreciate it muchly. 

(I've done a fair amount of open source contribution, so I get there is no obligation to get it done, but hopefully you like the idea enough :)

**Comment by werty1st** [comment]
Unfortunately, it's not possible to load a normal website into the side panel. An iFrame is possible, but I don't think it's a viable solution.

I found some references to an experimental feature-flag which enables a webview in the side panel, but couldn't find it in the current stable or canary versions of Chrome.

- https://www.newsdirectory3.com/you-can-now-open-web-pages-in-the-sidebar-of-the-chrome-browser-helentech/
- https://www.askvg.com/play-dinosaur-game-and-open-websites-in-chrome-side-panel/

If you need that kind of feature you should checkout https://vivaldi.com.
Its included by default.

**Comment by jussi01** [comment]
Hi! 

Thanks for the answer - however it is very much possible - see this extension (souurce also on github) https://webextension.org/listing/open-in-sidebar.html (although I havent checked if that is in an iframe, would surprise me).

In essence, I'm looking for a combination of your extension and that one... 

But once again, thanks for taking your time to look at it.

Jussi

**Comment by werty1st** [comment]
Hi, if you check the FAQ at point #4 it reads:

> Can I open any page in the sidebar view?
This extension enables the loading of webpages within an HTML iframe element, bypassing the default restriction set by the “X-Frame-Options: SAMEORIGIN” header....

With which website do you want to use the extension?
